version: 2.1

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
jobs:
  build:
    docker:
      - image: hubci/gotham:0.12
    steps:
      - checkout
      - run:
          name: "Build Website With Gotham"
          command: |
            HUGO_ENV=production gotham -v -s src/
      - run:
          name: "Test Website"
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: src
          paths:
            - public
  deploy:
    docker:
      - image: hubci/gotham:0.12
    steps:
      - attach_workspace:
          at: src
      - add_ssh_keys
      - run:
          name: "Deploy website"
          command: |
            echo 'sweb0.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHyIA/VJN9GHUeYUvauk+sGsQcvk8FpXErixwvgqQmW1pdje/Vo4RyAAskzdgoR+HUYOWM1gLW7ZFZHL8F//sqw=' >> ~/.ssh/known_hosts

            if [[ $CIRCLE_BRANCH == "trunk" ]]; then
              rsync -va --delete src/public/ root@sweb0.revidian.net:/static-websites/revidian-auto/launch/public_html
            fi
